name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Descarga el repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instala Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm install
        working-directory: ./app

      # 4. Corre tests
      - name: Run tests
        run: npm test
        working-directory: ./app

  build:
    runs-on: ubuntu-latest
    needs: test   # solo si test pasa

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 6. Build de la imagen usando tu Dockerfile
      - name: Build Docker image
        run: docker build -t miapp:latest .
        working-directory: ./

      # 7. (Opcional) Push a Docker Hub
      - name: Push image
        run: docker push miapp:latest
